#!/bin/bash
#
#  Copyright (c) 2023, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

OT_OPTIONS=(
    "-DOT_THREAD_VERSION=1.1"
    "-DOT_COVERAGE=OFF"
    "-DOT_CSL_RECEIVER=OFF"
    "-DOT_SRP_CLIENT=OFF"
    "-DOT_SRP_SERVER=OFF"
)
readonly OT_OPTIONS

die()
{
    echo " ** ERROR: $1"
    exit 1
}

cd openthread || die "Can't cd into openthread directory."
git checkout 0a5152b4fa9f9cbff57da89d9aa33d409e915241 || die "Can't git checkout v11/v12 codebase."
cd ..
rm -rf build || die "Can't remove the ./build directory."
./script/build ${OT_OPTIONS[@]} || die "Problem invoking ./script/build"
git submodule update
cp ./build/bin/ot-cli-ftd ./ot-versions/ot-cli-ftd_v11 || die "Copy of built FTD binary to ./ot-versions failed"
